import unittest
import itertools

from ti4nlp.lexica import generate_index_and_classifier, WordIndex, WordClassifier


def get_test_data():
    return {
        'noun': {
            'Infantry': ['inf', 'i', 'spec ops', 'letani warrior', 'letani', 'crimson legionnaire'],
            'Ground Force': ['gf'],
            'Mech': ['letani behemoth', 'aerie sentinel', 'dunlain reaper', 'scavenger zeta', 'ember colossus',
                     'pride of kenara', 'watcher', 'zs thunderbolt m2', 'icarus drive', 'annihilator', 'starlancer',
                     'moll terminus', 'iconoclast', 'eidolon', 'z-grav eidolon', 'mordred', 'quantum manipulator',
                     'valkyrie exoskeleton', 'hecatoncheries', 'shield paling', 'reanimator', 'reclaimer', 'indomitus',
                     "moyin's ashes", 'blackshade infiltrator'],
            'Fighter': ['ff', 'hybrid crystal fighter', 'crystal fighter', 'hcf', 'cf'],
            'Dreadnought': ['dread', 'super dreadnought', 'sdread', 'super dread', 'exotrireme'],
            'Destroyer': ['dd', 'strike wing alpha', 'swa', 'swing alpha', 'swing'],
            'Cruiser': ['saturn engine', 'saturn'],
            'Carrier': ['advanced carrier', 'adv carrier'],
            'Flagship': ['duha menaimon', 'quetzecoatl', 'arc secundus', 'son of ragh', 'artemiris', 'the inferno',
                         'wrath of kenara', 'dynamo', 'genesis', 'hil colish', '[0.0.1]', 'arvicon rex', 'fourth moon',
                         'matriarch', 'visz el vir', 'the alastor', 'memoria', "c'morran n'orr", 'ouranos',
                         'j.n.s. hylarim', 'the terror between', 'salai sai corian', 'loncarra ssodu', 'van hauge',
                         "y'sia y'ssarila"],
            'War Sun': ['ws', 'prototype war sun', 'proto war sun', 'pws'],
            'PDS': ['Planetary Defense System', 'hel titan'],
            'Space Dock': ['sd', 'dock', 'floating factory', 'dimensional tear'],
            'Mecatol Rex': ['mr', 'mecrex'],
            'Lirta IV': ['lirta4'],
            'Vefut II': ['vefut2'],
            'Rigel I': ['rigel1'],
            'Rigel II': ['rigel2'],
            'Rigel III': ['rigel3'],
            'Mordai II': ['mordai2'],
            **{k: [] for k in [
                'Nestphar', 'Arc Prime', 'Wren Terra', 'Lisis II', 'Ragh', 'Muaat', 'Hercant', 'Arretze', 'Kamdorn',
                'Jord', 'Creuss', '[0.0.0]', 'Moll Primus', 'Druaa', 'Maaluuk', "Tren'Lak", 'Quinarra', 'Jol', 'Nar',
                'Winnu', 'Archon Ren', 'Archon Tau', 'Darien', 'Retillion', 'Shalloq', 'Valk', 'Avar', 'Ylir',
                'The Dark', 'Ixth', 'Naazir', 'Rokha', 'Arcturus', 'Elysium', 'Acheron',
                'Abyz', 'Fria', 'Arinam', 'Meer', 'Arnor', 'Lor', 'Bereg', 'Centauri', 'Gral', 'Coorneeq',
                'Resculon', 'Dal Bootha', 'Xxehan', 'Lazar', 'Sakulag', 'Lodor', 'Mehar Xull', 'Mellon', 'Zohbat',
                'New Albion', 'Starpoint', 'Quann', "Qucen'n", 'Rarron', 'Saudor', "Tar'mann", "Tequ'ran", 'Torkan',
                'Thibah', 'Wellon', 'Archon Vail', 'Perimeter', 'Ang', 'Sem-Lore', 'Vorhal', 'Atlas', 'Primor',
                "Hope's End", 'Cormund', 'Everra', 'Jeol Ir', 'Accoen', 'Kraag', 'Siig', "Ba'kal", 'Alio Prima',
                'Lisis', 'Velnor', 'Cealdri', 'Xanhact', 'Vega Major', 'Vega Minor', 'Abaddon', 'Ashtroth', 'Loki',
                'Mallice', 'Mirage',
                *[a + 'a' for a in ['0', '1', '2', '3', '4']],
                *[a + b for a, b in itertools.product(['1', '2', '3', '4'], ['b', 'c', 'd', 'e', 'f'])],
                *[a + b for a, b in itertools.product(['2', '3', '4'], ['g', 'h', 'i', 'j', 'k', 'l'])],
                *[a + b for a, b in itertools.product(['3', '4'], ['m', 'n', 'o', 'p', 'q', 'r'])],
                *[a + b for a, b in itertools.product(['4'], ['s', 't', 'v', 'w', 'x', 'z'])],
            ]},
        },
        'verb': {
            'activate': [],
            'add': ['place'],
            'remove': ['destroy'],
            'move': [],
        },
        'qualifier': {
            '0': ['zero', 'no'],
            '1': ['one'],
            '2': ['two', 'couple'],
            '3': ['three'],
            '4': ['four'],
            '5': ['five'],
            '6': ['six', 'half dozen', 'half-dozen'],
            '7': ['seven'],
            '8': ['eight'],
            '9': ['nine'],
            '10': ['ten'],
            '11': ['eleven'],
            '12': ['twelve', 'dozen'],
            'each': ['every', 'any', 'all'],
            'damaged': ['sustained'],
            'exhausted': ['flipped'],
        },
        'conjunction': {
            'and': [],
            'then': [],
        },
        'preposition': {
            'to': ['onto'],
            'from': ['in', 'on'],
            'with': ['for', 'as'],
        },
        'skip_word': {
            'a': ['an'],
            'the': [],
        },
    }


def get_test_aliases():
    return {
        'Infantry': ['inf', 'i', 'spec ops', 'letani warrior', 'letani', 'crimson legionnaire'],
        'Ground Force': ['gf'],
        'Mech': ['letani behemoth', 'aerie sentinel', 'dunlain reaper', 'scavenger zeta', 'ember colossus',
                 'pride of kenara', 'watcher', 'zs thunderbolt m2', 'icarus drive', 'annihilator', 'starlancer',
                 'moll terminus', 'iconoclast', 'eidolon', 'z-grav eidolon', 'mordred', 'quantum manipulator',
                 'valkyrie exoskeleton', 'hecatoncheries', 'shield paling', 'reanimator', 'reclaimer', 'indomitus',
                 "moyin's ashes", 'blackshade infiltrator'],
        'Fighter': ['ff', 'hybrid crystal fighter', 'crystal fighter', 'hcf', 'cf'],
        'Dreadnought': ['dread', 'super dreadnought', 'sdread', 'super dread', 'exotrireme'],
        'Destroyer': ['dd', 'strike wing alpha', 'swa', 'swing alpha', 'swing'],
        'Cruiser': ['saturn engine', 'saturn'],
        'Carrier': ['advanced carrier', 'adv carrier'],
        'Flagship': ['duha menaimon', 'quetzecoatl', 'arc secundus', 'son of ragh', 'artemiris', 'the inferno',
                     'wrath of kenara', 'dynamo', 'genesis', 'hil colish', '[0.0.1]', 'arvicon rex', 'fourth moon',
                     'matriarch', 'visz el vir', 'the alastor', 'memoria', "c'morran n'orr", 'ouranos',
                     'j.n.s. hylarim', 'the terror between', 'salai sai corian', 'loncarra ssodu', 'van hauge',
                     "y'sia y'ssarila"],
        'War Sun': ['ws', 'prototype war sun', 'proto war sun', 'pws'],
        'PDS': ['Planetary Defense System', 'hel titan'],
        'Space Dock': ['sd', 'dock', 'floating factory', 'dimensional tear'],
        'Mecatol Rex': ['mr', 'mecrex'],
        'Lirta IV': ['lirta4'],
        'Vefut II': ['vefut2'],
        'Rigel I': ['rigel1'],
        'Rigel II': ['rigel2'],
        'Rigel III': ['rigel3'],
        'Mordai II': ['mordai2'],
        **{k: [] for k in [
            'Nestphar', 'Arc Prime', 'Wren Terra', 'Lisis II', 'Ragh', 'Muaat', 'Hercant', 'Arretze', 'Kamdorn',
            'Jord', 'Creuss', '[0.0.0]', 'Moll Primus', 'Druaa', 'Maaluuk', "Tren'Lak", 'Quinarra', 'Jol', 'Nar',
            'Winnu', 'Archon Ren', 'Archon Tau', 'Darien', 'Retillion', 'Shalloq',
            'Abyz', 'Fria', 'Arinam', 'Meer', 'Arnor', 'Lor', 'Bereg', 'Centauri', 'Gral', 'Coorneeq',
            'Resculon', 'Dal Bootha', 'Xxehan', 'Lazar', 'Sakulag', 'Lodor', 'Mehar Xull', 'Mellon', 'Zohbat',
            'New Albion', 'Starpoint', 'Quann', "Qucen'n", 'Rarron', 'Saudor', "Tar'mann", "Tequ'ran", 'Torkan',
            'Thibah', 'Wellon', 'Archon Vail', 'Perimeter', 'Ang', 'Sem-Lore', 'Vorhal', 'Atlas', 'Primor',
            "Hope's End", 'Cormund', 'Everra', 'Jeol Ir', 'Accoen', 'Kraag', 'Siig', "Ba'kal", 'Alio Prima',
            'Lisis', 'Velnor', 'Cealdri', 'Xanhact', 'Vega Major', 'Vega Minor', 'Abaddon', 'Ashtroth', 'Loki',
            'Mallice', 'Mirage',
            *[n + 'a' for n in ['0', '1', '2', '3', '4']],
            *[n + l for n, l in itertools.product(['1', '2', '3', '4'], ['b', 'c', 'd', 'e', 'f'])],
            *[n + l for n, l in itertools.product(['2', '3', '4'], ['g', 'h', 'i', 'j', 'k', 'l'])],
            *[n + l for n, l in itertools.product(['3', '4'], ['m', 'n', 'o', 'p', 'q', 'r'])],
            *[n + l for n, l in itertools.product(['4'], ['s', 't', 'v', 'w', 'x', 'z'])],
        ]},
        'activate': [],
        'add': ['place'],
        'remove': ['destroy'],
        'move': [],
        '0': ['zero', 'no'],
        '1': ['one'],
        '2': ['two', 'couple'],
        '3': ['three'],
        '4': ['four'],
        '5': ['five'],
        '6': ['six', 'half dozen', 'half-dozen'],
        '7': ['seven'],
        '8': ['eight'],
        '9': ['nine'],
        '10': ['ten'],
        '11': ['eleven'],
        '12': ['twelve', 'dozen'],
        'each': ['every', 'any', 'all'],
        'damaged': ['sustained'],
        'exhausted': ['flipped'],
        'and': [],
        'then': [],
        'to': [],
        'from': ['in'],
        'on': [],
        'with': ['for', 'as'],
        'a': ['an'],
        'the': [],
    }


def get_test_classifications():
    return {
        'noun': ['Infantry', 'Ground Force', 'Mech', 'Fighter', 'Dreadnought', 'Destroyer', 'Cruiser', 'Carrier',
                 'Flagship', 'War Sun', 'PDS', 'Space Dock', 'Mecatol Rex', 'Lirta IV', 'Vefut II', 'Rigel I',
                 'Rigel II', 'Rigel III', 'Mordai II', 'Nestphar', 'Arc Prime', 'Wren Terra', 'Lisis II', 'Ragh',
                 'Muaat', 'Hercant', 'Arretze', 'Kamdorn', 'Jord', 'Creuss', '[0.0.0]', 'Moll Primus', 'Druaa',
                 'Maaluuk', "Tren'Lak", 'Quinarra', 'Jol', 'Nar', 'Winnu', 'Archon Ren', 'Archon Tau', 'Darien',
                 'Retillion', 'Shalloq', 'Abyz', 'Fria', 'Arinam', 'Meer', 'Arnor', 'Lor', 'Bereg', 'Centauri', 'Gral',
                 'Coorneeq', 'Resculon', 'Dal Bootha', 'Xxehan', 'Lazar', 'Sakulag', 'Lodor', 'Mehar Xull', 'Mellon',
                 'Zohbat', 'New Albion', 'Starpoint', 'Quann', "Qucen'n", 'Rarron', 'Saudor', "Tar'mann", "Tequ'ran",
                 'Torkan', 'Thibah', 'Wellon', 'Archon Vail', 'Perimeter', 'Ang', 'Sem-Lore', 'Vorhal', 'Atlas',
                 'Primor', "Hope's End", 'Cormund', 'Everra', 'Jeol Ir', 'Accoen', 'Kraag', 'Siig', "Ba'kal",
                 'Alio Prima', 'Lisis', 'Velnor', 'Cealdri', 'Xanhact', 'Vega Major', 'Vega Minor', 'Abaddon',
                 'Ashtroth', 'Loki', 'Mallice', 'Mirage',
                 *[a + 'a' for a in ['0', '1', '2', '3', '4']],
                 *[a + b for a, b in itertools.product(['1', '2', '3', '4'], ['b', 'c', 'd', 'e', 'f'])],
                 *[a + b for a, b in itertools.product(['2', '3', '4'], ['g', 'h', 'i', 'j', 'k', 'l'])],
                 *[a + b for a, b in itertools.product(['3', '4'], ['m', 'n', 'o', 'p', 'q', 'r'])],
                 *[a + b for a, b in itertools.product(['4'], ['s', 't', 'v', 'w', 'x', 'z'])]],
        'verb': ['activate', 'add', 'remove', 'move'],
        'qualifier': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
                      'each', 'damaged', 'exhausted'],
        'conjunction': ['and', 'then'],
        'preposition': ['to', 'from', 'on', 'with'],
        'skip_word': ['a', 'the'],
    }


class LexicaTests(unittest.TestCase):
    def test_generate_index_and_classifier_does_as_expected(self):
        index1, classifier1 = generate_index_and_classifier(**get_test_data())
        index2 = WordIndex(**get_test_aliases())
        classifier2 = WordClassifier(**get_test_classifications())

        self.assertEqual(index1.alias_index, index2.alias_index,
                         f"Indexes didn't match: \n{index1.alias_index}\n{index2.alias_index}")
        self.assertEqual(classifier1.data, classifier2.data,
                         f"Classifiers didn't match: \n{classifier1.data}\n{classifier2.data}")


if __name__ == '__main__':
    unittest.main()
